@startuml

title Deployment for information System

left to right direction

node :<<Desktop1>>: as dk {
	node :<<OS>>: {
		component [Rich Web Application1]
	}
}

interface Keyboard

interface Mouse

Keyboard -- dk

Mouse -- dk

@enduml

