@startuml 
title Usecase for Information system
left to right direction
skinparam packageStyle rect

actor User

rectangle {
  User --> (User Authorization)
  (Food Order) ..> (User Authorization) : <<include>>
  (Cahs Check) ..> (User Authorization) : <<include>>
  (Course Order) ..> (User Authorization) : <<include>>
}
@enduml
